package com.ridehailing.common.error;

import org.springframework.http.HttpStatus;

/** Domain error vocabulary. The HTTP status is an attribute of the code. */
public enum ErrorCode {

    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    MALFORMED_REQUEST(HttpStatus.BAD_REQUEST),
    MISSING_REQUEST_HEADER(HttpStatus.BAD_REQUEST),

    UNAUTHENTICATED(HttpStatus.UNAUTHORIZED),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    ACCOUNT_SUSPENDED(HttpStatus.FORBIDDEN),

    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    EMAIL_ALREADY_REGISTERED(HttpStatus.CONFLICT),
    PHONE_ALREADY_REGISTERED(HttpStatus.CONFLICT),

    DRIVER_NOT_FOUND(HttpStatus.NOT_FOUND),
    DRIVER_PROFILE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    DRIVER_HAS_ACTIVE_RIDE(HttpStatus.CONFLICT),
    LICENSE_ALREADY_REGISTERED(HttpStatus.CONFLICT),
    INVALID_DRIVER_STATUS_TRANSITION(HttpStatus.CONFLICT),

    VEHICLE_NOT_FOUND(HttpStatus.NOT_FOUND),
    VEHICLE_ALREADY_REGISTERED(HttpStatus.CONFLICT),
    DRIVER_HAS_NO_ACTIVE_VEHICLE(HttpStatus.CONFLICT),

    RIDE_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVALID_RIDE_STATE_TRANSITION(HttpStatus.CONFLICT),
    NO_DRIVER_IN_RADIUS(HttpStatus.NOT_FOUND),
    INVALID_TRIP(HttpStatus.BAD_REQUEST),
    RIDE_OFFER_NOT_FOUND(HttpStatus.NOT_FOUND),
    RIDE_OFFER_ALREADY_RESOLVED(HttpStatus.CONFLICT),

    COUPON_NOT_FOUND(HttpStatus.NOT_FOUND),
    COUPON_ALREADY_EXISTS(HttpStatus.CONFLICT),
    COUPON_INACTIVE(HttpStatus.UNPROCESSABLE_ENTITY),
    COUPON_EXPIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    COUPON_NOT_APPLICABLE(HttpStatus.UNPROCESSABLE_ENTITY),
    COUPON_EXHAUSTED(HttpStatus.UNPROCESSABLE_ENTITY),

    // A declined payment is not an error but a FAILED row and a 200; these are the impossible requests.
    PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    PAYMENT_ALREADY_SETTLED(HttpStatus.CONFLICT),
    UNSUPPORTED_PAYMENT_METHOD(HttpStatus.BAD_REQUEST),

    PRICING_RULE_NOT_FOUND(HttpStatus.NOT_FOUND),
    PRICING_RULE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    PRICING_RULE_INVALID(HttpStatus.BAD_REQUEST),

    CONFIGURATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    CONFIGURATION_NOT_EDITABLE(HttpStatus.CONFLICT),
    CONFIGURATION_VALUE_INVALID(HttpStatus.BAD_REQUEST),

    IDEMPOTENCY_KEY_REUSED(HttpStatus.UNPROCESSABLE_ENTITY),
    REQUEST_ALREADY_IN_PROGRESS(HttpStatus.CONFLICT),
    CONCURRENT_MODIFICATION(HttpStatus.CONFLICT),
    DATA_INTEGRITY_VIOLATION(HttpStatus.CONFLICT),

    RATE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),

    DEPENDENCY_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus httpStatus;

    ErrorCode(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }
}
